#step 3 create a workflow
name: CI workflow
#step 4 add event triggers
on:
  push:
    #run the workflow on every push to the main branch
    branches: [ "main" ]
  pull_request:
    #Run the workflow whenever a pull request is created to the main branch
    branches: [ "main" ]
#add a job
jobs: 
    #name job build
    build:
      #tell github actions to use the latest ubuntu runner
      runs-on: ububtu-latest
      container: python:3.9-slim
      #Task 2
      steps:
      - name: Checkout
        #Task 2 Step 2
        uses: actions/checkout@v3
      #Task 2 Step 3
      #Add a new named step after the checkout step. Name this step ```Install dependencies```.
      - name: Install Dependencies
      #Next, you want to run the commands to update the package manager ```pip``` and then install the  dependencies.
      #Since there are two commands, you can run these inline using the ```run:```  keyword with the pipe ```|``` operator
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      #Task 2 Part 4
      - name: Lint with Flake8
        #add 2 commands to activate flake scan
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      #Task 2 Part 5
      - name: Run Unit tests with nose
      #run nosetests command to test your code and report on code coverage
        run:  nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
